<?php
/**
 * AdminGetUsage200ResponseDataMetrics
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Savanto\AI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Savanto API
 *
 * The Savanto REST API gives you programmatic access to AI-powered search, chat, recommendations, and content management.  ## Authentication All endpoints require a valid API key passed via the `Authorization` header: ``` Authorization: Bearer <api_key> ```  Key types: - **Secret keys** (`if_sk_...`) — Full API access. Use server-side only. - **Publishable keys** (`if_pk_...`) — Limited to search, chat, and feedback. Safe for client-side.
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Savanto\AI\Model;

use \ArrayAccess;
use \Savanto\AI\ObjectSerializer;

/**
 * AdminGetUsage200ResponseDataMetrics Class Doc Comment
 *
 * @category Class
 * @package  Savanto\AI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AdminGetUsage200ResponseDataMetrics implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'adminGetUsage_200_response_data_metrics';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'chat_messages' => '\Savanto\AI\Model\AdminGetUsage200ResponseDataMetricsChatMessages',
        'search_queries' => '\Savanto\AI\Model\AdminGetUsage200ResponseDataMetricsChatMessages',
        'recommendations' => '\Savanto\AI\Model\AdminGetUsage200ResponseDataMetricsChatMessages',
        'crawled_pages' => '\Savanto\AI\Model\AdminGetUsage200ResponseDataMetricsChatMessages',
        'pages_indexed' => '\Savanto\AI\Model\AdminGetUsage200ResponseDataMetricsChatMessages',
        'products_indexed' => '\Savanto\AI\Model\AdminGetUsage200ResponseDataMetricsChatMessages',
        'webhook_deliveries' => '\Savanto\AI\Model\AdminGetUsage200ResponseDataMetricsChatMessages'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'chat_messages' => null,
        'search_queries' => null,
        'recommendations' => null,
        'crawled_pages' => null,
        'pages_indexed' => null,
        'products_indexed' => null,
        'webhook_deliveries' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'chat_messages' => false,
        'search_queries' => false,
        'recommendations' => false,
        'crawled_pages' => false,
        'pages_indexed' => false,
        'products_indexed' => false,
        'webhook_deliveries' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'chat_messages' => 'chatMessages',
        'search_queries' => 'searchQueries',
        'recommendations' => 'recommendations',
        'crawled_pages' => 'crawledPages',
        'pages_indexed' => 'pagesIndexed',
        'products_indexed' => 'productsIndexed',
        'webhook_deliveries' => 'webhookDeliveries'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'chat_messages' => 'setChatMessages',
        'search_queries' => 'setSearchQueries',
        'recommendations' => 'setRecommendations',
        'crawled_pages' => 'setCrawledPages',
        'pages_indexed' => 'setPagesIndexed',
        'products_indexed' => 'setProductsIndexed',
        'webhook_deliveries' => 'setWebhookDeliveries'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'chat_messages' => 'getChatMessages',
        'search_queries' => 'getSearchQueries',
        'recommendations' => 'getRecommendations',
        'crawled_pages' => 'getCrawledPages',
        'pages_indexed' => 'getPagesIndexed',
        'products_indexed' => 'getProductsIndexed',
        'webhook_deliveries' => 'getWebhookDeliveries'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('chat_messages', $data ?? [], null);
        $this->setIfExists('search_queries', $data ?? [], null);
        $this->setIfExists('recommendations', $data ?? [], null);
        $this->setIfExists('crawled_pages', $data ?? [], null);
        $this->setIfExists('pages_indexed', $data ?? [], null);
        $this->setIfExists('products_indexed', $data ?? [], null);
        $this->setIfExists('webhook_deliveries', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['chat_messages'] === null) {
            $invalidProperties[] = "'chat_messages' can't be null";
        }
        if ($this->container['search_queries'] === null) {
            $invalidProperties[] = "'search_queries' can't be null";
        }
        if ($this->container['recommendations'] === null) {
            $invalidProperties[] = "'recommendations' can't be null";
        }
        if ($this->container['crawled_pages'] === null) {
            $invalidProperties[] = "'crawled_pages' can't be null";
        }
        if ($this->container['pages_indexed'] === null) {
            $invalidProperties[] = "'pages_indexed' can't be null";
        }
        if ($this->container['products_indexed'] === null) {
            $invalidProperties[] = "'products_indexed' can't be null";
        }
        if ($this->container['webhook_deliveries'] === null) {
            $invalidProperties[] = "'webhook_deliveries' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets chat_messages
     *
     * @return \Savanto\AI\Model\AdminGetUsage200ResponseDataMetricsChatMessages
     */
    public function getChatMessages()
    {
        return $this->container['chat_messages'];
    }

    /**
     * Sets chat_messages
     *
     * @param \Savanto\AI\Model\AdminGetUsage200ResponseDataMetricsChatMessages $chat_messages chat_messages
     *
     * @return self
     */
    public function setChatMessages($chat_messages)
    {
        if (is_null($chat_messages)) {
            throw new \InvalidArgumentException('non-nullable chat_messages cannot be null');
        }
        $this->container['chat_messages'] = $chat_messages;

        return $this;
    }

    /**
     * Gets search_queries
     *
     * @return \Savanto\AI\Model\AdminGetUsage200ResponseDataMetricsChatMessages
     */
    public function getSearchQueries()
    {
        return $this->container['search_queries'];
    }

    /**
     * Sets search_queries
     *
     * @param \Savanto\AI\Model\AdminGetUsage200ResponseDataMetricsChatMessages $search_queries search_queries
     *
     * @return self
     */
    public function setSearchQueries($search_queries)
    {
        if (is_null($search_queries)) {
            throw new \InvalidArgumentException('non-nullable search_queries cannot be null');
        }
        $this->container['search_queries'] = $search_queries;

        return $this;
    }

    /**
     * Gets recommendations
     *
     * @return \Savanto\AI\Model\AdminGetUsage200ResponseDataMetricsChatMessages
     */
    public function getRecommendations()
    {
        return $this->container['recommendations'];
    }

    /**
     * Sets recommendations
     *
     * @param \Savanto\AI\Model\AdminGetUsage200ResponseDataMetricsChatMessages $recommendations recommendations
     *
     * @return self
     */
    public function setRecommendations($recommendations)
    {
        if (is_null($recommendations)) {
            throw new \InvalidArgumentException('non-nullable recommendations cannot be null');
        }
        $this->container['recommendations'] = $recommendations;

        return $this;
    }

    /**
     * Gets crawled_pages
     *
     * @return \Savanto\AI\Model\AdminGetUsage200ResponseDataMetricsChatMessages
     */
    public function getCrawledPages()
    {
        return $this->container['crawled_pages'];
    }

    /**
     * Sets crawled_pages
     *
     * @param \Savanto\AI\Model\AdminGetUsage200ResponseDataMetricsChatMessages $crawled_pages crawled_pages
     *
     * @return self
     */
    public function setCrawledPages($crawled_pages)
    {
        if (is_null($crawled_pages)) {
            throw new \InvalidArgumentException('non-nullable crawled_pages cannot be null');
        }
        $this->container['crawled_pages'] = $crawled_pages;

        return $this;
    }

    /**
     * Gets pages_indexed
     *
     * @return \Savanto\AI\Model\AdminGetUsage200ResponseDataMetricsChatMessages
     */
    public function getPagesIndexed()
    {
        return $this->container['pages_indexed'];
    }

    /**
     * Sets pages_indexed
     *
     * @param \Savanto\AI\Model\AdminGetUsage200ResponseDataMetricsChatMessages $pages_indexed pages_indexed
     *
     * @return self
     */
    public function setPagesIndexed($pages_indexed)
    {
        if (is_null($pages_indexed)) {
            throw new \InvalidArgumentException('non-nullable pages_indexed cannot be null');
        }
        $this->container['pages_indexed'] = $pages_indexed;

        return $this;
    }

    /**
     * Gets products_indexed
     *
     * @return \Savanto\AI\Model\AdminGetUsage200ResponseDataMetricsChatMessages
     */
    public function getProductsIndexed()
    {
        return $this->container['products_indexed'];
    }

    /**
     * Sets products_indexed
     *
     * @param \Savanto\AI\Model\AdminGetUsage200ResponseDataMetricsChatMessages $products_indexed products_indexed
     *
     * @return self
     */
    public function setProductsIndexed($products_indexed)
    {
        if (is_null($products_indexed)) {
            throw new \InvalidArgumentException('non-nullable products_indexed cannot be null');
        }
        $this->container['products_indexed'] = $products_indexed;

        return $this;
    }

    /**
     * Gets webhook_deliveries
     *
     * @return \Savanto\AI\Model\AdminGetUsage200ResponseDataMetricsChatMessages
     */
    public function getWebhookDeliveries()
    {
        return $this->container['webhook_deliveries'];
    }

    /**
     * Sets webhook_deliveries
     *
     * @param \Savanto\AI\Model\AdminGetUsage200ResponseDataMetricsChatMessages $webhook_deliveries webhook_deliveries
     *
     * @return self
     */
    public function setWebhookDeliveries($webhook_deliveries)
    {
        if (is_null($webhook_deliveries)) {
            throw new \InvalidArgumentException('non-nullable webhook_deliveries cannot be null');
        }
        $this->container['webhook_deliveries'] = $webhook_deliveries;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


