<?php
/**
 * CreateCustomDomainRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Savanto\AI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Savanto API
 *
 * The Savanto REST API gives you programmatic access to AI-powered search, chat, recommendations, and content management.  ## Authentication All endpoints require a valid API key passed via the `Authorization` header: ``` Authorization: Bearer <api_key> ```  Key types: - **Secret keys** (`if_sk_...`) — Full API access. Use server-side only. - **Publishable keys** (`if_pk_...`) — Limited to search, chat, and feedback. Safe for client-side.
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Savanto\AI\Model;

use \ArrayAccess;
use \Savanto\AI\ObjectSerializer;

/**
 * CreateCustomDomainRequest Class Doc Comment
 *
 * @category Class
 * @package  Savanto\AI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CreateCustomDomainRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'createCustomDomain_request';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'name' => 'string',
        'classifier_prompt' => 'string',
        'agent_prompt' => 'string',
        'mcp_servers' => '\Savanto\AI\Model\CreateCustomDomainRequestMcpServersInner[]',
        'api_endpoints' => '\Savanto\AI\Model\CreateCustomDomainRequestApiEndpointsInner[]',
        'progress_message' => 'string',
        'enabled' => 'bool',
        'tool_strategy' => 'string',
        'max_tool_turns' => 'int'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'name' => null,
        'classifier_prompt' => null,
        'agent_prompt' => null,
        'mcp_servers' => null,
        'api_endpoints' => null,
        'progress_message' => null,
        'enabled' => null,
        'tool_strategy' => null,
        'max_tool_turns' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'name' => false,
        'classifier_prompt' => false,
        'agent_prompt' => false,
        'mcp_servers' => false,
        'api_endpoints' => false,
        'progress_message' => false,
        'enabled' => false,
        'tool_strategy' => false,
        'max_tool_turns' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
        'classifier_prompt' => 'classifierPrompt',
        'agent_prompt' => 'agentPrompt',
        'mcp_servers' => 'mcpServers',
        'api_endpoints' => 'apiEndpoints',
        'progress_message' => 'progressMessage',
        'enabled' => 'enabled',
        'tool_strategy' => 'toolStrategy',
        'max_tool_turns' => 'maxToolTurns'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'classifier_prompt' => 'setClassifierPrompt',
        'agent_prompt' => 'setAgentPrompt',
        'mcp_servers' => 'setMcpServers',
        'api_endpoints' => 'setApiEndpoints',
        'progress_message' => 'setProgressMessage',
        'enabled' => 'setEnabled',
        'tool_strategy' => 'setToolStrategy',
        'max_tool_turns' => 'setMaxToolTurns'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'classifier_prompt' => 'getClassifierPrompt',
        'agent_prompt' => 'getAgentPrompt',
        'mcp_servers' => 'getMcpServers',
        'api_endpoints' => 'getApiEndpoints',
        'progress_message' => 'getProgressMessage',
        'enabled' => 'getEnabled',
        'tool_strategy' => 'getToolStrategy',
        'max_tool_turns' => 'getMaxToolTurns'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const TOOL_STRATEGY_REQUIRED = 'required';
    public const TOOL_STRATEGY_AUTO = 'auto';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getToolStrategyAllowableValues()
    {
        return [
            self::TOOL_STRATEGY_REQUIRED,
            self::TOOL_STRATEGY_AUTO,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('classifier_prompt', $data ?? [], null);
        $this->setIfExists('agent_prompt', $data ?? [], null);
        $this->setIfExists('mcp_servers', $data ?? [], null);
        $this->setIfExists('api_endpoints', $data ?? [], null);
        $this->setIfExists('progress_message', $data ?? [], null);
        $this->setIfExists('enabled', $data ?? [], false);
        $this->setIfExists('tool_strategy', $data ?? [], null);
        $this->setIfExists('max_tool_turns', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) > 50)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 50.";
        }

        if ((mb_strlen($this->container['name']) < 3)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be bigger than or equal to 3.";
        }

        if ($this->container['classifier_prompt'] === null) {
            $invalidProperties[] = "'classifier_prompt' can't be null";
        }
        if ((mb_strlen($this->container['classifier_prompt']) > 500)) {
            $invalidProperties[] = "invalid value for 'classifier_prompt', the character length must be smaller than or equal to 500.";
        }

        if ((mb_strlen($this->container['classifier_prompt']) < 10)) {
            $invalidProperties[] = "invalid value for 'classifier_prompt', the character length must be bigger than or equal to 10.";
        }

        if ($this->container['agent_prompt'] === null) {
            $invalidProperties[] = "'agent_prompt' can't be null";
        }
        if ((mb_strlen($this->container['agent_prompt']) > 10000)) {
            $invalidProperties[] = "invalid value for 'agent_prompt', the character length must be smaller than or equal to 10000.";
        }

        if ((mb_strlen($this->container['agent_prompt']) < 20)) {
            $invalidProperties[] = "invalid value for 'agent_prompt', the character length must be bigger than or equal to 20.";
        }

        if ($this->container['mcp_servers'] === null) {
            $invalidProperties[] = "'mcp_servers' can't be null";
        }
        if ((count($this->container['mcp_servers']) > 5)) {
            $invalidProperties[] = "invalid value for 'mcp_servers', number of items must be less than or equal to 5.";
        }

        if (!is_null($this->container['api_endpoints']) && (count($this->container['api_endpoints']) > 3)) {
            $invalidProperties[] = "invalid value for 'api_endpoints', number of items must be less than or equal to 3.";
        }

        if ($this->container['progress_message'] === null) {
            $invalidProperties[] = "'progress_message' can't be null";
        }
        if ((mb_strlen($this->container['progress_message']) > 100)) {
            $invalidProperties[] = "invalid value for 'progress_message', the character length must be smaller than or equal to 100.";
        }

        if ((mb_strlen($this->container['progress_message']) < 5)) {
            $invalidProperties[] = "invalid value for 'progress_message', the character length must be bigger than or equal to 5.";
        }

        $allowedValues = $this->getToolStrategyAllowableValues();
        if (!is_null($this->container['tool_strategy']) && !in_array($this->container['tool_strategy'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'tool_strategy', must be one of '%s'",
                $this->container['tool_strategy'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['max_tool_turns']) && ($this->container['max_tool_turns'] > 5)) {
            $invalidProperties[] = "invalid value for 'max_tool_turns', must be smaller than or equal to 5.";
        }

        if (!is_null($this->container['max_tool_turns']) && ($this->container['max_tool_turns'] < 1)) {
            $invalidProperties[] = "invalid value for 'max_tool_turns', must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        if ((mb_strlen($name) > 50)) {
            throw new \InvalidArgumentException('invalid length for $name when calling CreateCustomDomainRequest., must be smaller than or equal to 50.');
        }
        if ((mb_strlen($name) < 3)) {
            throw new \InvalidArgumentException('invalid length for $name when calling CreateCustomDomainRequest., must be bigger than or equal to 3.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets classifier_prompt
     *
     * @return string
     */
    public function getClassifierPrompt()
    {
        return $this->container['classifier_prompt'];
    }

    /**
     * Sets classifier_prompt
     *
     * @param string $classifier_prompt classifier_prompt
     *
     * @return self
     */
    public function setClassifierPrompt($classifier_prompt)
    {
        if (is_null($classifier_prompt)) {
            throw new \InvalidArgumentException('non-nullable classifier_prompt cannot be null');
        }
        if ((mb_strlen($classifier_prompt) > 500)) {
            throw new \InvalidArgumentException('invalid length for $classifier_prompt when calling CreateCustomDomainRequest., must be smaller than or equal to 500.');
        }
        if ((mb_strlen($classifier_prompt) < 10)) {
            throw new \InvalidArgumentException('invalid length for $classifier_prompt when calling CreateCustomDomainRequest., must be bigger than or equal to 10.');
        }

        $this->container['classifier_prompt'] = $classifier_prompt;

        return $this;
    }

    /**
     * Gets agent_prompt
     *
     * @return string
     */
    public function getAgentPrompt()
    {
        return $this->container['agent_prompt'];
    }

    /**
     * Sets agent_prompt
     *
     * @param string $agent_prompt agent_prompt
     *
     * @return self
     */
    public function setAgentPrompt($agent_prompt)
    {
        if (is_null($agent_prompt)) {
            throw new \InvalidArgumentException('non-nullable agent_prompt cannot be null');
        }
        if ((mb_strlen($agent_prompt) > 10000)) {
            throw new \InvalidArgumentException('invalid length for $agent_prompt when calling CreateCustomDomainRequest., must be smaller than or equal to 10000.');
        }
        if ((mb_strlen($agent_prompt) < 20)) {
            throw new \InvalidArgumentException('invalid length for $agent_prompt when calling CreateCustomDomainRequest., must be bigger than or equal to 20.');
        }

        $this->container['agent_prompt'] = $agent_prompt;

        return $this;
    }

    /**
     * Gets mcp_servers
     *
     * @return \Savanto\AI\Model\CreateCustomDomainRequestMcpServersInner[]
     */
    public function getMcpServers()
    {
        return $this->container['mcp_servers'];
    }

    /**
     * Sets mcp_servers
     *
     * @param \Savanto\AI\Model\CreateCustomDomainRequestMcpServersInner[] $mcp_servers mcp_servers
     *
     * @return self
     */
    public function setMcpServers($mcp_servers)
    {
        if (is_null($mcp_servers)) {
            throw new \InvalidArgumentException('non-nullable mcp_servers cannot be null');
        }

        if ((count($mcp_servers) > 5)) {
            throw new \InvalidArgumentException('invalid value for $mcp_servers when calling CreateCustomDomainRequest., number of items must be less than or equal to 5.');
        }
        $this->container['mcp_servers'] = $mcp_servers;

        return $this;
    }

    /**
     * Gets api_endpoints
     *
     * @return \Savanto\AI\Model\CreateCustomDomainRequestApiEndpointsInner[]|null
     */
    public function getApiEndpoints()
    {
        return $this->container['api_endpoints'];
    }

    /**
     * Sets api_endpoints
     *
     * @param \Savanto\AI\Model\CreateCustomDomainRequestApiEndpointsInner[]|null $api_endpoints api_endpoints
     *
     * @return self
     */
    public function setApiEndpoints($api_endpoints)
    {
        if (is_null($api_endpoints)) {
            throw new \InvalidArgumentException('non-nullable api_endpoints cannot be null');
        }

        if ((count($api_endpoints) > 3)) {
            throw new \InvalidArgumentException('invalid value for $api_endpoints when calling CreateCustomDomainRequest., number of items must be less than or equal to 3.');
        }
        $this->container['api_endpoints'] = $api_endpoints;

        return $this;
    }

    /**
     * Gets progress_message
     *
     * @return string
     */
    public function getProgressMessage()
    {
        return $this->container['progress_message'];
    }

    /**
     * Sets progress_message
     *
     * @param string $progress_message progress_message
     *
     * @return self
     */
    public function setProgressMessage($progress_message)
    {
        if (is_null($progress_message)) {
            throw new \InvalidArgumentException('non-nullable progress_message cannot be null');
        }
        if ((mb_strlen($progress_message) > 100)) {
            throw new \InvalidArgumentException('invalid length for $progress_message when calling CreateCustomDomainRequest., must be smaller than or equal to 100.');
        }
        if ((mb_strlen($progress_message) < 5)) {
            throw new \InvalidArgumentException('invalid length for $progress_message when calling CreateCustomDomainRequest., must be bigger than or equal to 5.');
        }

        $this->container['progress_message'] = $progress_message;

        return $this;
    }

    /**
     * Gets enabled
     *
     * @return bool|null
     */
    public function getEnabled()
    {
        return $this->container['enabled'];
    }

    /**
     * Sets enabled
     *
     * @param bool|null $enabled enabled
     *
     * @return self
     */
    public function setEnabled($enabled)
    {
        if (is_null($enabled)) {
            throw new \InvalidArgumentException('non-nullable enabled cannot be null');
        }
        $this->container['enabled'] = $enabled;

        return $this;
    }

    /**
     * Gets tool_strategy
     *
     * @return string|null
     */
    public function getToolStrategy()
    {
        return $this->container['tool_strategy'];
    }

    /**
     * Sets tool_strategy
     *
     * @param string|null $tool_strategy tool_strategy
     *
     * @return self
     */
    public function setToolStrategy($tool_strategy)
    {
        if (is_null($tool_strategy)) {
            throw new \InvalidArgumentException('non-nullable tool_strategy cannot be null');
        }
        $allowedValues = $this->getToolStrategyAllowableValues();
        if (!in_array($tool_strategy, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'tool_strategy', must be one of '%s'",
                    $tool_strategy,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['tool_strategy'] = $tool_strategy;

        return $this;
    }

    /**
     * Gets max_tool_turns
     *
     * @return int|null
     */
    public function getMaxToolTurns()
    {
        return $this->container['max_tool_turns'];
    }

    /**
     * Sets max_tool_turns
     *
     * @param int|null $max_tool_turns max_tool_turns
     *
     * @return self
     */
    public function setMaxToolTurns($max_tool_turns)
    {
        if (is_null($max_tool_turns)) {
            throw new \InvalidArgumentException('non-nullable max_tool_turns cannot be null');
        }

        if (($max_tool_turns > 5)) {
            throw new \InvalidArgumentException('invalid value for $max_tool_turns when calling CreateCustomDomainRequest., must be smaller than or equal to 5.');
        }
        if (($max_tool_turns < 1)) {
            throw new \InvalidArgumentException('invalid value for $max_tool_turns when calling CreateCustomDomainRequest., must be bigger than or equal to 1.');
        }

        $this->container['max_tool_turns'] = $max_tool_turns;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


