<?php
/**
 * CreateWebhookInputRetryPolicy
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Savanto\AI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Savanto API
 *
 * The Savanto REST API gives you programmatic access to AI-powered search, chat, recommendations, and content management.  ## Authentication All endpoints require a valid API key passed via the `Authorization` header: ``` Authorization: Bearer <api_key> ```  Key types: - **Secret keys** (`if_sk_...`) — Full API access. Use server-side only. - **Publishable keys** (`if_pk_...`) — Limited to search, chat, and feedback. Safe for client-side.
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Savanto\AI\Model;

use \ArrayAccess;
use \Savanto\AI\ObjectSerializer;

/**
 * CreateWebhookInputRetryPolicy Class Doc Comment
 *
 * @category Class
 * @package  Savanto\AI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CreateWebhookInputRetryPolicy implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'CreateWebhookInput_retryPolicy';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'max_attempts' => 'int',
        'backoff_strategy' => 'string',
        'initial_delay_ms' => 'int',
        'max_delay_ms' => 'int'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'max_attempts' => null,
        'backoff_strategy' => null,
        'initial_delay_ms' => null,
        'max_delay_ms' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'max_attempts' => false,
        'backoff_strategy' => false,
        'initial_delay_ms' => false,
        'max_delay_ms' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'max_attempts' => 'maxAttempts',
        'backoff_strategy' => 'backoffStrategy',
        'initial_delay_ms' => 'initialDelayMs',
        'max_delay_ms' => 'maxDelayMs'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'max_attempts' => 'setMaxAttempts',
        'backoff_strategy' => 'setBackoffStrategy',
        'initial_delay_ms' => 'setInitialDelayMs',
        'max_delay_ms' => 'setMaxDelayMs'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'max_attempts' => 'getMaxAttempts',
        'backoff_strategy' => 'getBackoffStrategy',
        'initial_delay_ms' => 'getInitialDelayMs',
        'max_delay_ms' => 'getMaxDelayMs'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const BACKOFF_STRATEGY_LINEAR = 'linear';
    public const BACKOFF_STRATEGY_EXPONENTIAL = 'exponential';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getBackoffStrategyAllowableValues()
    {
        return [
            self::BACKOFF_STRATEGY_LINEAR,
            self::BACKOFF_STRATEGY_EXPONENTIAL,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('max_attempts', $data ?? [], null);
        $this->setIfExists('backoff_strategy', $data ?? [], null);
        $this->setIfExists('initial_delay_ms', $data ?? [], null);
        $this->setIfExists('max_delay_ms', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['max_attempts']) && ($this->container['max_attempts'] > 10)) {
            $invalidProperties[] = "invalid value for 'max_attempts', must be smaller than or equal to 10.";
        }

        if (!is_null($this->container['max_attempts']) && ($this->container['max_attempts'] < 1)) {
            $invalidProperties[] = "invalid value for 'max_attempts', must be bigger than or equal to 1.";
        }

        $allowedValues = $this->getBackoffStrategyAllowableValues();
        if (!is_null($this->container['backoff_strategy']) && !in_array($this->container['backoff_strategy'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'backoff_strategy', must be one of '%s'",
                $this->container['backoff_strategy'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['initial_delay_ms']) && ($this->container['initial_delay_ms'] < 100)) {
            $invalidProperties[] = "invalid value for 'initial_delay_ms', must be bigger than or equal to 100.";
        }

        if (!is_null($this->container['max_delay_ms']) && ($this->container['max_delay_ms'] < 1000)) {
            $invalidProperties[] = "invalid value for 'max_delay_ms', must be bigger than or equal to 1000.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets max_attempts
     *
     * @return int|null
     */
    public function getMaxAttempts()
    {
        return $this->container['max_attempts'];
    }

    /**
     * Sets max_attempts
     *
     * @param int|null $max_attempts max_attempts
     *
     * @return self
     */
    public function setMaxAttempts($max_attempts)
    {
        if (is_null($max_attempts)) {
            throw new \InvalidArgumentException('non-nullable max_attempts cannot be null');
        }

        if (($max_attempts > 10)) {
            throw new \InvalidArgumentException('invalid value for $max_attempts when calling CreateWebhookInputRetryPolicy., must be smaller than or equal to 10.');
        }
        if (($max_attempts < 1)) {
            throw new \InvalidArgumentException('invalid value for $max_attempts when calling CreateWebhookInputRetryPolicy., must be bigger than or equal to 1.');
        }

        $this->container['max_attempts'] = $max_attempts;

        return $this;
    }

    /**
     * Gets backoff_strategy
     *
     * @return string|null
     */
    public function getBackoffStrategy()
    {
        return $this->container['backoff_strategy'];
    }

    /**
     * Sets backoff_strategy
     *
     * @param string|null $backoff_strategy backoff_strategy
     *
     * @return self
     */
    public function setBackoffStrategy($backoff_strategy)
    {
        if (is_null($backoff_strategy)) {
            throw new \InvalidArgumentException('non-nullable backoff_strategy cannot be null');
        }
        $allowedValues = $this->getBackoffStrategyAllowableValues();
        if (!in_array($backoff_strategy, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'backoff_strategy', must be one of '%s'",
                    $backoff_strategy,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['backoff_strategy'] = $backoff_strategy;

        return $this;
    }

    /**
     * Gets initial_delay_ms
     *
     * @return int|null
     */
    public function getInitialDelayMs()
    {
        return $this->container['initial_delay_ms'];
    }

    /**
     * Sets initial_delay_ms
     *
     * @param int|null $initial_delay_ms initial_delay_ms
     *
     * @return self
     */
    public function setInitialDelayMs($initial_delay_ms)
    {
        if (is_null($initial_delay_ms)) {
            throw new \InvalidArgumentException('non-nullable initial_delay_ms cannot be null');
        }

        if (($initial_delay_ms < 100)) {
            throw new \InvalidArgumentException('invalid value for $initial_delay_ms when calling CreateWebhookInputRetryPolicy., must be bigger than or equal to 100.');
        }

        $this->container['initial_delay_ms'] = $initial_delay_ms;

        return $this;
    }

    /**
     * Gets max_delay_ms
     *
     * @return int|null
     */
    public function getMaxDelayMs()
    {
        return $this->container['max_delay_ms'];
    }

    /**
     * Sets max_delay_ms
     *
     * @param int|null $max_delay_ms max_delay_ms
     *
     * @return self
     */
    public function setMaxDelayMs($max_delay_ms)
    {
        if (is_null($max_delay_ms)) {
            throw new \InvalidArgumentException('non-nullable max_delay_ms cannot be null');
        }

        if (($max_delay_ms < 1000)) {
            throw new \InvalidArgumentException('invalid value for $max_delay_ms when calling CreateWebhookInputRetryPolicy., must be bigger than or equal to 1000.');
        }

        $this->container['max_delay_ms'] = $max_delay_ms;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


