<?php
/**
 * PostInput
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Savanto\AI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Savanto API
 *
 * The Savanto REST API gives you programmatic access to AI-powered search, chat, recommendations, and content management.  ## Authentication All endpoints require a valid API key passed via the `Authorization` header: ``` Authorization: Bearer <api_key> ```  Key types: - **Secret keys** (`if_sk_...`) — Full API access. Use server-side only. - **Publishable keys** (`if_pk_...`) — Limited to search, chat, and feedback. Safe for client-side.
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Savanto\AI\Model;

use \ArrayAccess;
use \Savanto\AI\ObjectSerializer;

/**
 * PostInput Class Doc Comment
 *
 * @category Class
 * @package  Savanto\AI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PostInput implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'PostInput';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'id' => 'string',
        'title' => 'string',
        'content' => 'string',
        'searchable_text' => 'string',
        'excerpt' => 'string',
        'post_type' => 'string',
        'status' => 'string',
        'author_id' => 'string',
        'author_name' => 'string',
        'published_at' => 'string',
        'categories' => 'string[]',
        'tags' => 'string[]',
        'url' => 'string',
        'featured_image' => 'string',
        'source' => 'string',
        'index_status' => 'string',
        'metadata' => 'array<string,\Savanto\AI\Model\PostInputMetadataValue>',
        'attributes' => 'array<string,mixed>'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'id' => null,
        'title' => null,
        'content' => null,
        'searchable_text' => null,
        'excerpt' => null,
        'post_type' => null,
        'status' => null,
        'author_id' => null,
        'author_name' => null,
        'published_at' => null,
        'categories' => null,
        'tags' => null,
        'url' => null,
        'featured_image' => null,
        'source' => null,
        'index_status' => null,
        'metadata' => null,
        'attributes' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'id' => false,
        'title' => false,
        'content' => false,
        'searchable_text' => false,
        'excerpt' => false,
        'post_type' => false,
        'status' => false,
        'author_id' => false,
        'author_name' => false,
        'published_at' => false,
        'categories' => false,
        'tags' => false,
        'url' => false,
        'featured_image' => false,
        'source' => false,
        'index_status' => false,
        'metadata' => false,
        'attributes' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'title' => 'title',
        'content' => 'content',
        'searchable_text' => 'searchableText',
        'excerpt' => 'excerpt',
        'post_type' => 'postType',
        'status' => 'status',
        'author_id' => 'authorId',
        'author_name' => 'authorName',
        'published_at' => 'publishedAt',
        'categories' => 'categories',
        'tags' => 'tags',
        'url' => 'url',
        'featured_image' => 'featuredImage',
        'source' => 'source',
        'index_status' => 'indexStatus',
        'metadata' => 'metadata',
        'attributes' => 'attributes'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'title' => 'setTitle',
        'content' => 'setContent',
        'searchable_text' => 'setSearchableText',
        'excerpt' => 'setExcerpt',
        'post_type' => 'setPostType',
        'status' => 'setStatus',
        'author_id' => 'setAuthorId',
        'author_name' => 'setAuthorName',
        'published_at' => 'setPublishedAt',
        'categories' => 'setCategories',
        'tags' => 'setTags',
        'url' => 'setUrl',
        'featured_image' => 'setFeaturedImage',
        'source' => 'setSource',
        'index_status' => 'setIndexStatus',
        'metadata' => 'setMetadata',
        'attributes' => 'setAttributes'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'title' => 'getTitle',
        'content' => 'getContent',
        'searchable_text' => 'getSearchableText',
        'excerpt' => 'getExcerpt',
        'post_type' => 'getPostType',
        'status' => 'getStatus',
        'author_id' => 'getAuthorId',
        'author_name' => 'getAuthorName',
        'published_at' => 'getPublishedAt',
        'categories' => 'getCategories',
        'tags' => 'getTags',
        'url' => 'getUrl',
        'featured_image' => 'getFeaturedImage',
        'source' => 'getSource',
        'index_status' => 'getIndexStatus',
        'metadata' => 'getMetadata',
        'attributes' => 'getAttributes'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const STATUS_PUBLISH = 'publish';
    public const STATUS_DRAFT = 'draft';
    public const STATUS__PRIVATE = 'private';
    public const STATUS_PENDING = 'pending';
    public const INDEX_STATUS_ACTIVE = 'active';
    public const INDEX_STATUS_HIDDEN = 'hidden';
    public const INDEX_STATUS_DISABLED = 'disabled';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_PUBLISH,
            self::STATUS_DRAFT,
            self::STATUS__PRIVATE,
            self::STATUS_PENDING,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getIndexStatusAllowableValues()
    {
        return [
            self::INDEX_STATUS_ACTIVE,
            self::INDEX_STATUS_HIDDEN,
            self::INDEX_STATUS_DISABLED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('content', $data ?? [], null);
        $this->setIfExists('searchable_text', $data ?? [], null);
        $this->setIfExists('excerpt', $data ?? [], null);
        $this->setIfExists('post_type', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('author_id', $data ?? [], null);
        $this->setIfExists('author_name', $data ?? [], null);
        $this->setIfExists('published_at', $data ?? [], null);
        $this->setIfExists('categories', $data ?? [], null);
        $this->setIfExists('tags', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('featured_image', $data ?? [], null);
        $this->setIfExists('source', $data ?? [], null);
        $this->setIfExists('index_status', $data ?? [], null);
        $this->setIfExists('metadata', $data ?? [], null);
        $this->setIfExists('attributes', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ((mb_strlen($this->container['id']) > 255)) {
            $invalidProperties[] = "invalid value for 'id', the character length must be smaller than or equal to 255.";
        }

        if ((mb_strlen($this->container['id']) < 1)) {
            $invalidProperties[] = "invalid value for 'id', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['title'] === null) {
            $invalidProperties[] = "'title' can't be null";
        }
        if ((mb_strlen($this->container['title']) > 500)) {
            $invalidProperties[] = "invalid value for 'title', the character length must be smaller than or equal to 500.";
        }

        if ((mb_strlen($this->container['title']) < 1)) {
            $invalidProperties[] = "invalid value for 'title', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['content']) && (mb_strlen($this->container['content']) > 200000)) {
            $invalidProperties[] = "invalid value for 'content', the character length must be smaller than or equal to 200000.";
        }

        if (!is_null($this->container['searchable_text']) && (mb_strlen($this->container['searchable_text']) > 200000)) {
            $invalidProperties[] = "invalid value for 'searchable_text', the character length must be smaller than or equal to 200000.";
        }

        if (!is_null($this->container['excerpt']) && (mb_strlen($this->container['excerpt']) > 1000)) {
            $invalidProperties[] = "invalid value for 'excerpt', the character length must be smaller than or equal to 1000.";
        }

        if (!is_null($this->container['post_type']) && (mb_strlen($this->container['post_type']) > 100)) {
            $invalidProperties[] = "invalid value for 'post_type', the character length must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['post_type']) && (mb_strlen($this->container['post_type']) < 1)) {
            $invalidProperties[] = "invalid value for 'post_type', the character length must be bigger than or equal to 1.";
        }

        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['author_id']) && (mb_strlen($this->container['author_id']) > 100)) {
            $invalidProperties[] = "invalid value for 'author_id', the character length must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['author_name']) && (mb_strlen($this->container['author_name']) > 200)) {
            $invalidProperties[] = "invalid value for 'author_name', the character length must be smaller than or equal to 200.";
        }

        if (!is_null($this->container['source']) && (mb_strlen($this->container['source']) > 50)) {
            $invalidProperties[] = "invalid value for 'source', the character length must be smaller than or equal to 50.";
        }

        $allowedValues = $this->getIndexStatusAllowableValues();
        if (!is_null($this->container['index_status']) && !in_array($this->container['index_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'index_status', must be one of '%s'",
                $this->container['index_status'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        if ((mb_strlen($id) > 255)) {
            throw new \InvalidArgumentException('invalid length for $id when calling PostInput., must be smaller than or equal to 255.');
        }
        if ((mb_strlen($id) < 1)) {
            throw new \InvalidArgumentException('invalid length for $id when calling PostInput., must be bigger than or equal to 1.');
        }

        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string $title title
     *
     * @return self
     */
    public function setTitle($title)
    {
        if (is_null($title)) {
            throw new \InvalidArgumentException('non-nullable title cannot be null');
        }
        if ((mb_strlen($title) > 500)) {
            throw new \InvalidArgumentException('invalid length for $title when calling PostInput., must be smaller than or equal to 500.');
        }
        if ((mb_strlen($title) < 1)) {
            throw new \InvalidArgumentException('invalid length for $title when calling PostInput., must be bigger than or equal to 1.');
        }

        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets content
     *
     * @return string|null
     */
    public function getContent()
    {
        return $this->container['content'];
    }

    /**
     * Sets content
     *
     * @param string|null $content content
     *
     * @return self
     */
    public function setContent($content)
    {
        if (is_null($content)) {
            throw new \InvalidArgumentException('non-nullable content cannot be null');
        }
        if ((mb_strlen($content) > 200000)) {
            throw new \InvalidArgumentException('invalid length for $content when calling PostInput., must be smaller than or equal to 200000.');
        }

        $this->container['content'] = $content;

        return $this;
    }

    /**
     * Gets searchable_text
     *
     * @return string|null
     */
    public function getSearchableText()
    {
        return $this->container['searchable_text'];
    }

    /**
     * Sets searchable_text
     *
     * @param string|null $searchable_text searchable_text
     *
     * @return self
     */
    public function setSearchableText($searchable_text)
    {
        if (is_null($searchable_text)) {
            throw new \InvalidArgumentException('non-nullable searchable_text cannot be null');
        }
        if ((mb_strlen($searchable_text) > 200000)) {
            throw new \InvalidArgumentException('invalid length for $searchable_text when calling PostInput., must be smaller than or equal to 200000.');
        }

        $this->container['searchable_text'] = $searchable_text;

        return $this;
    }

    /**
     * Gets excerpt
     *
     * @return string|null
     */
    public function getExcerpt()
    {
        return $this->container['excerpt'];
    }

    /**
     * Sets excerpt
     *
     * @param string|null $excerpt excerpt
     *
     * @return self
     */
    public function setExcerpt($excerpt)
    {
        if (is_null($excerpt)) {
            throw new \InvalidArgumentException('non-nullable excerpt cannot be null');
        }
        if ((mb_strlen($excerpt) > 1000)) {
            throw new \InvalidArgumentException('invalid length for $excerpt when calling PostInput., must be smaller than or equal to 1000.');
        }

        $this->container['excerpt'] = $excerpt;

        return $this;
    }

    /**
     * Gets post_type
     *
     * @return string|null
     */
    public function getPostType()
    {
        return $this->container['post_type'];
    }

    /**
     * Sets post_type
     *
     * @param string|null $post_type post_type
     *
     * @return self
     */
    public function setPostType($post_type)
    {
        if (is_null($post_type)) {
            throw new \InvalidArgumentException('non-nullable post_type cannot be null');
        }
        if ((mb_strlen($post_type) > 100)) {
            throw new \InvalidArgumentException('invalid length for $post_type when calling PostInput., must be smaller than or equal to 100.');
        }
        if ((mb_strlen($post_type) < 1)) {
            throw new \InvalidArgumentException('invalid length for $post_type when calling PostInput., must be bigger than or equal to 1.');
        }

        $this->container['post_type'] = $post_type;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets author_id
     *
     * @return string|null
     */
    public function getAuthorId()
    {
        return $this->container['author_id'];
    }

    /**
     * Sets author_id
     *
     * @param string|null $author_id author_id
     *
     * @return self
     */
    public function setAuthorId($author_id)
    {
        if (is_null($author_id)) {
            throw new \InvalidArgumentException('non-nullable author_id cannot be null');
        }
        if ((mb_strlen($author_id) > 100)) {
            throw new \InvalidArgumentException('invalid length for $author_id when calling PostInput., must be smaller than or equal to 100.');
        }

        $this->container['author_id'] = $author_id;

        return $this;
    }

    /**
     * Gets author_name
     *
     * @return string|null
     */
    public function getAuthorName()
    {
        return $this->container['author_name'];
    }

    /**
     * Sets author_name
     *
     * @param string|null $author_name author_name
     *
     * @return self
     */
    public function setAuthorName($author_name)
    {
        if (is_null($author_name)) {
            throw new \InvalidArgumentException('non-nullable author_name cannot be null');
        }
        if ((mb_strlen($author_name) > 200)) {
            throw new \InvalidArgumentException('invalid length for $author_name when calling PostInput., must be smaller than or equal to 200.');
        }

        $this->container['author_name'] = $author_name;

        return $this;
    }

    /**
     * Gets published_at
     *
     * @return string|null
     */
    public function getPublishedAt()
    {
        return $this->container['published_at'];
    }

    /**
     * Sets published_at
     *
     * @param string|null $published_at published_at
     *
     * @return self
     */
    public function setPublishedAt($published_at)
    {
        if (is_null($published_at)) {
            throw new \InvalidArgumentException('non-nullable published_at cannot be null');
        }
        $this->container['published_at'] = $published_at;

        return $this;
    }

    /**
     * Gets categories
     *
     * @return string[]|null
     */
    public function getCategories()
    {
        return $this->container['categories'];
    }

    /**
     * Sets categories
     *
     * @param string[]|null $categories categories
     *
     * @return self
     */
    public function setCategories($categories)
    {
        if (is_null($categories)) {
            throw new \InvalidArgumentException('non-nullable categories cannot be null');
        }
        $this->container['categories'] = $categories;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return string[]|null
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param string[]|null $tags tags
     *
     * @return self
     */
    public function setTags($tags)
    {
        if (is_null($tags)) {
            throw new \InvalidArgumentException('non-nullable tags cannot be null');
        }
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string|null
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string|null $url url
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            throw new \InvalidArgumentException('non-nullable url cannot be null');
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets featured_image
     *
     * @return string|null
     */
    public function getFeaturedImage()
    {
        return $this->container['featured_image'];
    }

    /**
     * Sets featured_image
     *
     * @param string|null $featured_image featured_image
     *
     * @return self
     */
    public function setFeaturedImage($featured_image)
    {
        if (is_null($featured_image)) {
            throw new \InvalidArgumentException('non-nullable featured_image cannot be null');
        }
        $this->container['featured_image'] = $featured_image;

        return $this;
    }

    /**
     * Gets source
     *
     * @return string|null
     */
    public function getSource()
    {
        return $this->container['source'];
    }

    /**
     * Sets source
     *
     * @param string|null $source source
     *
     * @return self
     */
    public function setSource($source)
    {
        if (is_null($source)) {
            throw new \InvalidArgumentException('non-nullable source cannot be null');
        }
        if ((mb_strlen($source) > 50)) {
            throw new \InvalidArgumentException('invalid length for $source when calling PostInput., must be smaller than or equal to 50.');
        }

        $this->container['source'] = $source;

        return $this;
    }

    /**
     * Gets index_status
     *
     * @return string|null
     */
    public function getIndexStatus()
    {
        return $this->container['index_status'];
    }

    /**
     * Sets index_status
     *
     * @param string|null $index_status index_status
     *
     * @return self
     */
    public function setIndexStatus($index_status)
    {
        if (is_null($index_status)) {
            throw new \InvalidArgumentException('non-nullable index_status cannot be null');
        }
        $allowedValues = $this->getIndexStatusAllowableValues();
        if (!in_array($index_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'index_status', must be one of '%s'",
                    $index_status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['index_status'] = $index_status;

        return $this;
    }

    /**
     * Gets metadata
     *
     * @return array<string,\Savanto\AI\Model\PostInputMetadataValue>|null
     */
    public function getMetadata()
    {
        return $this->container['metadata'];
    }

    /**
     * Sets metadata
     *
     * @param array<string,\Savanto\AI\Model\PostInputMetadataValue>|null $metadata metadata
     *
     * @return self
     */
    public function setMetadata($metadata)
    {
        if (is_null($metadata)) {
            throw new \InvalidArgumentException('non-nullable metadata cannot be null');
        }
        $this->container['metadata'] = $metadata;

        return $this;
    }

    /**
     * Gets attributes
     *
     * @return array<string,mixed>|null
     */
    public function getAttributes()
    {
        return $this->container['attributes'];
    }

    /**
     * Sets attributes
     *
     * @param array<string,mixed>|null $attributes attributes
     *
     * @return self
     */
    public function setAttributes($attributes)
    {
        if (is_null($attributes)) {
            throw new \InvalidArgumentException('non-nullable attributes cannot be null');
        }
        $this->container['attributes'] = $attributes;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


