<?php
/**
 * PromptInput
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Savanto\AI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Savanto API
 *
 * The Savanto REST API gives you programmatic access to AI-powered search, chat, recommendations, and content management.  ## Authentication All endpoints require a valid API key passed via the `Authorization` header: ``` Authorization: Bearer <api_key> ```  Key types: - **Secret keys** (`if_sk_...`) — Full API access. Use server-side only. - **Publishable keys** (`if_pk_...`) — Limited to search, chat, and feedback. Safe for client-side.
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Savanto\AI\Model;

use \ArrayAccess;
use \Savanto\AI\ObjectSerializer;

/**
 * PromptInput Class Doc Comment
 *
 * @category Class
 * @package  Savanto\AI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PromptInput implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'PromptInput';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'id' => 'string',
        'prompt' => 'string',
        'title' => 'string',
        'description' => 'string',
        'canned_response' => 'string',
        'response_format' => 'string',
        'override_mode' => 'string',
        'post_ids' => 'string[]',
        'product_ids' => 'string[]',
        'follow_up_ids' => 'string[]',
        'tags' => 'string[]',
        'categories' => 'string[]',
        'status' => 'string',
        'priority' => 'int',
        'icon' => 'string',
        'active_from' => 'string',
        'active_to' => 'string',
        'metadata' => 'array<string,mixed>'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'id' => null,
        'prompt' => null,
        'title' => null,
        'description' => null,
        'canned_response' => null,
        'response_format' => null,
        'override_mode' => null,
        'post_ids' => null,
        'product_ids' => null,
        'follow_up_ids' => null,
        'tags' => null,
        'categories' => null,
        'status' => null,
        'priority' => null,
        'icon' => null,
        'active_from' => null,
        'active_to' => null,
        'metadata' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'id' => false,
        'prompt' => false,
        'title' => false,
        'description' => false,
        'canned_response' => false,
        'response_format' => false,
        'override_mode' => false,
        'post_ids' => false,
        'product_ids' => false,
        'follow_up_ids' => false,
        'tags' => false,
        'categories' => false,
        'status' => false,
        'priority' => false,
        'icon' => false,
        'active_from' => false,
        'active_to' => false,
        'metadata' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'prompt' => 'prompt',
        'title' => 'title',
        'description' => 'description',
        'canned_response' => 'cannedResponse',
        'response_format' => 'responseFormat',
        'override_mode' => 'overrideMode',
        'post_ids' => 'postIds',
        'product_ids' => 'productIds',
        'follow_up_ids' => 'followUpIds',
        'tags' => 'tags',
        'categories' => 'categories',
        'status' => 'status',
        'priority' => 'priority',
        'icon' => 'icon',
        'active_from' => 'activeFrom',
        'active_to' => 'activeTo',
        'metadata' => 'metadata'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'prompt' => 'setPrompt',
        'title' => 'setTitle',
        'description' => 'setDescription',
        'canned_response' => 'setCannedResponse',
        'response_format' => 'setResponseFormat',
        'override_mode' => 'setOverrideMode',
        'post_ids' => 'setPostIds',
        'product_ids' => 'setProductIds',
        'follow_up_ids' => 'setFollowUpIds',
        'tags' => 'setTags',
        'categories' => 'setCategories',
        'status' => 'setStatus',
        'priority' => 'setPriority',
        'icon' => 'setIcon',
        'active_from' => 'setActiveFrom',
        'active_to' => 'setActiveTo',
        'metadata' => 'setMetadata'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'prompt' => 'getPrompt',
        'title' => 'getTitle',
        'description' => 'getDescription',
        'canned_response' => 'getCannedResponse',
        'response_format' => 'getResponseFormat',
        'override_mode' => 'getOverrideMode',
        'post_ids' => 'getPostIds',
        'product_ids' => 'getProductIds',
        'follow_up_ids' => 'getFollowUpIds',
        'tags' => 'getTags',
        'categories' => 'getCategories',
        'status' => 'getStatus',
        'priority' => 'getPriority',
        'icon' => 'getIcon',
        'active_from' => 'getActiveFrom',
        'active_to' => 'getActiveTo',
        'metadata' => 'getMetadata'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const RESPONSE_FORMAT_MARKDOWN = 'markdown';
    public const RESPONSE_FORMAT_TEXT = 'text';
    public const RESPONSE_FORMAT_HTML = 'html';
    public const OVERRIDE_MODE_OVERRIDE = 'override';
    public const OVERRIDE_MODE_FALLBACK = 'fallback';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getResponseFormatAllowableValues()
    {
        return [
            self::RESPONSE_FORMAT_MARKDOWN,
            self::RESPONSE_FORMAT_TEXT,
            self::RESPONSE_FORMAT_HTML,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getOverrideModeAllowableValues()
    {
        return [
            self::OVERRIDE_MODE_OVERRIDE,
            self::OVERRIDE_MODE_FALLBACK,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('prompt', $data ?? [], null);
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('canned_response', $data ?? [], null);
        $this->setIfExists('response_format', $data ?? [], null);
        $this->setIfExists('override_mode', $data ?? [], null);
        $this->setIfExists('post_ids', $data ?? [], null);
        $this->setIfExists('product_ids', $data ?? [], null);
        $this->setIfExists('follow_up_ids', $data ?? [], null);
        $this->setIfExists('tags', $data ?? [], null);
        $this->setIfExists('categories', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('priority', $data ?? [], null);
        $this->setIfExists('icon', $data ?? [], null);
        $this->setIfExists('active_from', $data ?? [], null);
        $this->setIfExists('active_to', $data ?? [], null);
        $this->setIfExists('metadata', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['id']) && (mb_strlen($this->container['id']) > 100)) {
            $invalidProperties[] = "invalid value for 'id', the character length must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['id']) && (mb_strlen($this->container['id']) < 1)) {
            $invalidProperties[] = "invalid value for 'id', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['prompt'] === null) {
            $invalidProperties[] = "'prompt' can't be null";
        }
        if ((mb_strlen($this->container['prompt']) > 1000)) {
            $invalidProperties[] = "invalid value for 'prompt', the character length must be smaller than or equal to 1000.";
        }

        if ((mb_strlen($this->container['prompt']) < 1)) {
            $invalidProperties[] = "invalid value for 'prompt', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['title']) && (mb_strlen($this->container['title']) > 200)) {
            $invalidProperties[] = "invalid value for 'title', the character length must be smaller than or equal to 200.";
        }

        if (!is_null($this->container['description']) && (mb_strlen($this->container['description']) > 500)) {
            $invalidProperties[] = "invalid value for 'description', the character length must be smaller than or equal to 500.";
        }

        if (!is_null($this->container['canned_response']) && (mb_strlen($this->container['canned_response']) > 5000)) {
            $invalidProperties[] = "invalid value for 'canned_response', the character length must be smaller than or equal to 5000.";
        }

        $allowedValues = $this->getResponseFormatAllowableValues();
        if (!is_null($this->container['response_format']) && !in_array($this->container['response_format'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'response_format', must be one of '%s'",
                $this->container['response_format'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getOverrideModeAllowableValues();
        if (!is_null($this->container['override_mode']) && !in_array($this->container['override_mode'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'override_mode', must be one of '%s'",
                $this->container['override_mode'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['post_ids']) && (count($this->container['post_ids']) > 50)) {
            $invalidProperties[] = "invalid value for 'post_ids', number of items must be less than or equal to 50.";
        }

        if (!is_null($this->container['product_ids']) && (count($this->container['product_ids']) > 50)) {
            $invalidProperties[] = "invalid value for 'product_ids', number of items must be less than or equal to 50.";
        }

        if (!is_null($this->container['follow_up_ids']) && (count($this->container['follow_up_ids']) > 20)) {
            $invalidProperties[] = "invalid value for 'follow_up_ids', number of items must be less than or equal to 20.";
        }

        if (!is_null($this->container['tags']) && (count($this->container['tags']) > 20)) {
            $invalidProperties[] = "invalid value for 'tags', number of items must be less than or equal to 20.";
        }

        if (!is_null($this->container['categories']) && (count($this->container['categories']) > 10)) {
            $invalidProperties[] = "invalid value for 'categories', number of items must be less than or equal to 10.";
        }

        if (!is_null($this->container['status']) && (mb_strlen($this->container['status']) > 50)) {
            $invalidProperties[] = "invalid value for 'status', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['priority']) && ($this->container['priority'] > 9999)) {
            $invalidProperties[] = "invalid value for 'priority', must be smaller than or equal to 9999.";
        }

        if (!is_null($this->container['priority']) && ($this->container['priority'] < 0)) {
            $invalidProperties[] = "invalid value for 'priority', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['icon']) && (mb_strlen($this->container['icon']) > 10)) {
            $invalidProperties[] = "invalid value for 'icon', the character length must be smaller than or equal to 10.";
        }

        if (!is_null($this->container['active_from']) && (mb_strlen($this->container['active_from']) > 50)) {
            $invalidProperties[] = "invalid value for 'active_from', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['active_to']) && (mb_strlen($this->container['active_to']) > 50)) {
            $invalidProperties[] = "invalid value for 'active_to', the character length must be smaller than or equal to 50.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        if ((mb_strlen($id) > 100)) {
            throw new \InvalidArgumentException('invalid length for $id when calling PromptInput., must be smaller than or equal to 100.');
        }
        if ((mb_strlen($id) < 1)) {
            throw new \InvalidArgumentException('invalid length for $id when calling PromptInput., must be bigger than or equal to 1.');
        }

        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets prompt
     *
     * @return string
     */
    public function getPrompt()
    {
        return $this->container['prompt'];
    }

    /**
     * Sets prompt
     *
     * @param string $prompt prompt
     *
     * @return self
     */
    public function setPrompt($prompt)
    {
        if (is_null($prompt)) {
            throw new \InvalidArgumentException('non-nullable prompt cannot be null');
        }
        if ((mb_strlen($prompt) > 1000)) {
            throw new \InvalidArgumentException('invalid length for $prompt when calling PromptInput., must be smaller than or equal to 1000.');
        }
        if ((mb_strlen($prompt) < 1)) {
            throw new \InvalidArgumentException('invalid length for $prompt when calling PromptInput., must be bigger than or equal to 1.');
        }

        $this->container['prompt'] = $prompt;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string|null
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string|null $title title
     *
     * @return self
     */
    public function setTitle($title)
    {
        if (is_null($title)) {
            throw new \InvalidArgumentException('non-nullable title cannot be null');
        }
        if ((mb_strlen($title) > 200)) {
            throw new \InvalidArgumentException('invalid length for $title when calling PromptInput., must be smaller than or equal to 200.');
        }

        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        if ((mb_strlen($description) > 500)) {
            throw new \InvalidArgumentException('invalid length for $description when calling PromptInput., must be smaller than or equal to 500.');
        }

        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets canned_response
     *
     * @return string|null
     */
    public function getCannedResponse()
    {
        return $this->container['canned_response'];
    }

    /**
     * Sets canned_response
     *
     * @param string|null $canned_response canned_response
     *
     * @return self
     */
    public function setCannedResponse($canned_response)
    {
        if (is_null($canned_response)) {
            throw new \InvalidArgumentException('non-nullable canned_response cannot be null');
        }
        if ((mb_strlen($canned_response) > 5000)) {
            throw new \InvalidArgumentException('invalid length for $canned_response when calling PromptInput., must be smaller than or equal to 5000.');
        }

        $this->container['canned_response'] = $canned_response;

        return $this;
    }

    /**
     * Gets response_format
     *
     * @return string|null
     */
    public function getResponseFormat()
    {
        return $this->container['response_format'];
    }

    /**
     * Sets response_format
     *
     * @param string|null $response_format response_format
     *
     * @return self
     */
    public function setResponseFormat($response_format)
    {
        if (is_null($response_format)) {
            throw new \InvalidArgumentException('non-nullable response_format cannot be null');
        }
        $allowedValues = $this->getResponseFormatAllowableValues();
        if (!in_array($response_format, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'response_format', must be one of '%s'",
                    $response_format,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['response_format'] = $response_format;

        return $this;
    }

    /**
     * Gets override_mode
     *
     * @return string|null
     */
    public function getOverrideMode()
    {
        return $this->container['override_mode'];
    }

    /**
     * Sets override_mode
     *
     * @param string|null $override_mode override_mode
     *
     * @return self
     */
    public function setOverrideMode($override_mode)
    {
        if (is_null($override_mode)) {
            throw new \InvalidArgumentException('non-nullable override_mode cannot be null');
        }
        $allowedValues = $this->getOverrideModeAllowableValues();
        if (!in_array($override_mode, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'override_mode', must be one of '%s'",
                    $override_mode,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['override_mode'] = $override_mode;

        return $this;
    }

    /**
     * Gets post_ids
     *
     * @return string[]|null
     */
    public function getPostIds()
    {
        return $this->container['post_ids'];
    }

    /**
     * Sets post_ids
     *
     * @param string[]|null $post_ids post_ids
     *
     * @return self
     */
    public function setPostIds($post_ids)
    {
        if (is_null($post_ids)) {
            throw new \InvalidArgumentException('non-nullable post_ids cannot be null');
        }

        if ((count($post_ids) > 50)) {
            throw new \InvalidArgumentException('invalid value for $post_ids when calling PromptInput., number of items must be less than or equal to 50.');
        }
        $this->container['post_ids'] = $post_ids;

        return $this;
    }

    /**
     * Gets product_ids
     *
     * @return string[]|null
     */
    public function getProductIds()
    {
        return $this->container['product_ids'];
    }

    /**
     * Sets product_ids
     *
     * @param string[]|null $product_ids product_ids
     *
     * @return self
     */
    public function setProductIds($product_ids)
    {
        if (is_null($product_ids)) {
            throw new \InvalidArgumentException('non-nullable product_ids cannot be null');
        }

        if ((count($product_ids) > 50)) {
            throw new \InvalidArgumentException('invalid value for $product_ids when calling PromptInput., number of items must be less than or equal to 50.');
        }
        $this->container['product_ids'] = $product_ids;

        return $this;
    }

    /**
     * Gets follow_up_ids
     *
     * @return string[]|null
     */
    public function getFollowUpIds()
    {
        return $this->container['follow_up_ids'];
    }

    /**
     * Sets follow_up_ids
     *
     * @param string[]|null $follow_up_ids follow_up_ids
     *
     * @return self
     */
    public function setFollowUpIds($follow_up_ids)
    {
        if (is_null($follow_up_ids)) {
            throw new \InvalidArgumentException('non-nullable follow_up_ids cannot be null');
        }

        if ((count($follow_up_ids) > 20)) {
            throw new \InvalidArgumentException('invalid value for $follow_up_ids when calling PromptInput., number of items must be less than or equal to 20.');
        }
        $this->container['follow_up_ids'] = $follow_up_ids;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return string[]|null
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param string[]|null $tags tags
     *
     * @return self
     */
    public function setTags($tags)
    {
        if (is_null($tags)) {
            throw new \InvalidArgumentException('non-nullable tags cannot be null');
        }

        if ((count($tags) > 20)) {
            throw new \InvalidArgumentException('invalid value for $tags when calling PromptInput., number of items must be less than or equal to 20.');
        }
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets categories
     *
     * @return string[]|null
     */
    public function getCategories()
    {
        return $this->container['categories'];
    }

    /**
     * Sets categories
     *
     * @param string[]|null $categories categories
     *
     * @return self
     */
    public function setCategories($categories)
    {
        if (is_null($categories)) {
            throw new \InvalidArgumentException('non-nullable categories cannot be null');
        }

        if ((count($categories) > 10)) {
            throw new \InvalidArgumentException('invalid value for $categories when calling PromptInput., number of items must be less than or equal to 10.');
        }
        $this->container['categories'] = $categories;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        if ((mb_strlen($status) > 50)) {
            throw new \InvalidArgumentException('invalid length for $status when calling PromptInput., must be smaller than or equal to 50.');
        }

        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets priority
     *
     * @return int|null
     */
    public function getPriority()
    {
        return $this->container['priority'];
    }

    /**
     * Sets priority
     *
     * @param int|null $priority priority
     *
     * @return self
     */
    public function setPriority($priority)
    {
        if (is_null($priority)) {
            throw new \InvalidArgumentException('non-nullable priority cannot be null');
        }

        if (($priority > 9999)) {
            throw new \InvalidArgumentException('invalid value for $priority when calling PromptInput., must be smaller than or equal to 9999.');
        }
        if (($priority < 0)) {
            throw new \InvalidArgumentException('invalid value for $priority when calling PromptInput., must be bigger than or equal to 0.');
        }

        $this->container['priority'] = $priority;

        return $this;
    }

    /**
     * Gets icon
     *
     * @return string|null
     */
    public function getIcon()
    {
        return $this->container['icon'];
    }

    /**
     * Sets icon
     *
     * @param string|null $icon icon
     *
     * @return self
     */
    public function setIcon($icon)
    {
        if (is_null($icon)) {
            throw new \InvalidArgumentException('non-nullable icon cannot be null');
        }
        if ((mb_strlen($icon) > 10)) {
            throw new \InvalidArgumentException('invalid length for $icon when calling PromptInput., must be smaller than or equal to 10.');
        }

        $this->container['icon'] = $icon;

        return $this;
    }

    /**
     * Gets active_from
     *
     * @return string|null
     */
    public function getActiveFrom()
    {
        return $this->container['active_from'];
    }

    /**
     * Sets active_from
     *
     * @param string|null $active_from active_from
     *
     * @return self
     */
    public function setActiveFrom($active_from)
    {
        if (is_null($active_from)) {
            throw new \InvalidArgumentException('non-nullable active_from cannot be null');
        }
        if ((mb_strlen($active_from) > 50)) {
            throw new \InvalidArgumentException('invalid length for $active_from when calling PromptInput., must be smaller than or equal to 50.');
        }

        $this->container['active_from'] = $active_from;

        return $this;
    }

    /**
     * Gets active_to
     *
     * @return string|null
     */
    public function getActiveTo()
    {
        return $this->container['active_to'];
    }

    /**
     * Sets active_to
     *
     * @param string|null $active_to active_to
     *
     * @return self
     */
    public function setActiveTo($active_to)
    {
        if (is_null($active_to)) {
            throw new \InvalidArgumentException('non-nullable active_to cannot be null');
        }
        if ((mb_strlen($active_to) > 50)) {
            throw new \InvalidArgumentException('invalid length for $active_to when calling PromptInput., must be smaller than or equal to 50.');
        }

        $this->container['active_to'] = $active_to;

        return $this;
    }

    /**
     * Gets metadata
     *
     * @return array<string,mixed>|null
     */
    public function getMetadata()
    {
        return $this->container['metadata'];
    }

    /**
     * Sets metadata
     *
     * @param array<string,mixed>|null $metadata metadata
     *
     * @return self
     */
    public function setMetadata($metadata)
    {
        if (is_null($metadata)) {
            throw new \InvalidArgumentException('non-nullable metadata cannot be null');
        }
        $this->container['metadata'] = $metadata;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


