<?php
/**
 * RecommendationRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Savanto\AI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Savanto API
 *
 * The Savanto REST API gives you programmatic access to AI-powered search, chat, recommendations, and content management.  ## Authentication All endpoints require a valid API key passed via the `Authorization` header: ``` Authorization: Bearer <api_key> ```  Key types: - **Secret keys** (`if_sk_...`) — Full API access. Use server-side only. - **Publishable keys** (`if_pk_...`) — Limited to search, chat, and feedback. Safe for client-side.
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Savanto\AI\Model;

use \ArrayAccess;
use \Savanto\AI\ObjectSerializer;

/**
 * RecommendationRequest Class Doc Comment
 *
 * @category Class
 * @package  Savanto\AI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RecommendationRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'RecommendationRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'product_id' => 'string',
        'basket_affinity' => '\Savanto\AI\Model\RecommendationRequestBasketAffinityInner[]',
        'complimentary_products' => 'string[]',
        'user_id' => 'string',
        'weights' => '\Savanto\AI\Model\RecommendationRequestWeights',
        'max_recommendations' => 'int',
        'exclude_product_ids' => 'string[]',
        'product_filter' => 'array<string,mixed>'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'product_id' => null,
        'basket_affinity' => null,
        'complimentary_products' => null,
        'user_id' => null,
        'weights' => null,
        'max_recommendations' => null,
        'exclude_product_ids' => null,
        'product_filter' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'product_id' => false,
        'basket_affinity' => false,
        'complimentary_products' => false,
        'user_id' => false,
        'weights' => false,
        'max_recommendations' => false,
        'exclude_product_ids' => false,
        'product_filter' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'product_id' => 'productId',
        'basket_affinity' => 'basketAffinity',
        'complimentary_products' => 'complimentaryProducts',
        'user_id' => 'userId',
        'weights' => 'weights',
        'max_recommendations' => 'maxRecommendations',
        'exclude_product_ids' => 'excludeProductIds',
        'product_filter' => 'productFilter'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'product_id' => 'setProductId',
        'basket_affinity' => 'setBasketAffinity',
        'complimentary_products' => 'setComplimentaryProducts',
        'user_id' => 'setUserId',
        'weights' => 'setWeights',
        'max_recommendations' => 'setMaxRecommendations',
        'exclude_product_ids' => 'setExcludeProductIds',
        'product_filter' => 'setProductFilter'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'product_id' => 'getProductId',
        'basket_affinity' => 'getBasketAffinity',
        'complimentary_products' => 'getComplimentaryProducts',
        'user_id' => 'getUserId',
        'weights' => 'getWeights',
        'max_recommendations' => 'getMaxRecommendations',
        'exclude_product_ids' => 'getExcludeProductIds',
        'product_filter' => 'getProductFilter'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('product_id', $data ?? [], null);
        $this->setIfExists('basket_affinity', $data ?? [], null);
        $this->setIfExists('complimentary_products', $data ?? [], null);
        $this->setIfExists('user_id', $data ?? [], null);
        $this->setIfExists('weights', $data ?? [], null);
        $this->setIfExists('max_recommendations', $data ?? [], 10);
        $this->setIfExists('exclude_product_ids', $data ?? [], null);
        $this->setIfExists('product_filter', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['product_id'] === null) {
            $invalidProperties[] = "'product_id' can't be null";
        }
        if ((mb_strlen($this->container['product_id']) < 1)) {
            $invalidProperties[] = "invalid value for 'product_id', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['user_id']) && (mb_strlen($this->container['user_id']) < 1)) {
            $invalidProperties[] = "invalid value for 'user_id', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['max_recommendations']) && ($this->container['max_recommendations'] > 50)) {
            $invalidProperties[] = "invalid value for 'max_recommendations', must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['max_recommendations']) && ($this->container['max_recommendations'] < 1)) {
            $invalidProperties[] = "invalid value for 'max_recommendations', must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets product_id
     *
     * @return string
     */
    public function getProductId()
    {
        return $this->container['product_id'];
    }

    /**
     * Sets product_id
     *
     * @param string $product_id product_id
     *
     * @return self
     */
    public function setProductId($product_id)
    {
        if (is_null($product_id)) {
            throw new \InvalidArgumentException('non-nullable product_id cannot be null');
        }

        if ((mb_strlen($product_id) < 1)) {
            throw new \InvalidArgumentException('invalid length for $product_id when calling RecommendationRequest., must be bigger than or equal to 1.');
        }

        $this->container['product_id'] = $product_id;

        return $this;
    }

    /**
     * Gets basket_affinity
     *
     * @return \Savanto\AI\Model\RecommendationRequestBasketAffinityInner[]|null
     */
    public function getBasketAffinity()
    {
        return $this->container['basket_affinity'];
    }

    /**
     * Sets basket_affinity
     *
     * @param \Savanto\AI\Model\RecommendationRequestBasketAffinityInner[]|null $basket_affinity basket_affinity
     *
     * @return self
     */
    public function setBasketAffinity($basket_affinity)
    {
        if (is_null($basket_affinity)) {
            throw new \InvalidArgumentException('non-nullable basket_affinity cannot be null');
        }
        $this->container['basket_affinity'] = $basket_affinity;

        return $this;
    }

    /**
     * Gets complimentary_products
     *
     * @return string[]|null
     */
    public function getComplimentaryProducts()
    {
        return $this->container['complimentary_products'];
    }

    /**
     * Sets complimentary_products
     *
     * @param string[]|null $complimentary_products complimentary_products
     *
     * @return self
     */
    public function setComplimentaryProducts($complimentary_products)
    {
        if (is_null($complimentary_products)) {
            throw new \InvalidArgumentException('non-nullable complimentary_products cannot be null');
        }
        $this->container['complimentary_products'] = $complimentary_products;

        return $this;
    }

    /**
     * Gets user_id
     *
     * @return string|null
     */
    public function getUserId()
    {
        return $this->container['user_id'];
    }

    /**
     * Sets user_id
     *
     * @param string|null $user_id user_id
     *
     * @return self
     */
    public function setUserId($user_id)
    {
        if (is_null($user_id)) {
            throw new \InvalidArgumentException('non-nullable user_id cannot be null');
        }

        if ((mb_strlen($user_id) < 1)) {
            throw new \InvalidArgumentException('invalid length for $user_id when calling RecommendationRequest., must be bigger than or equal to 1.');
        }

        $this->container['user_id'] = $user_id;

        return $this;
    }

    /**
     * Gets weights
     *
     * @return \Savanto\AI\Model\RecommendationRequestWeights|null
     */
    public function getWeights()
    {
        return $this->container['weights'];
    }

    /**
     * Sets weights
     *
     * @param \Savanto\AI\Model\RecommendationRequestWeights|null $weights weights
     *
     * @return self
     */
    public function setWeights($weights)
    {
        if (is_null($weights)) {
            throw new \InvalidArgumentException('non-nullable weights cannot be null');
        }
        $this->container['weights'] = $weights;

        return $this;
    }

    /**
     * Gets max_recommendations
     *
     * @return int|null
     */
    public function getMaxRecommendations()
    {
        return $this->container['max_recommendations'];
    }

    /**
     * Sets max_recommendations
     *
     * @param int|null $max_recommendations max_recommendations
     *
     * @return self
     */
    public function setMaxRecommendations($max_recommendations)
    {
        if (is_null($max_recommendations)) {
            throw new \InvalidArgumentException('non-nullable max_recommendations cannot be null');
        }

        if (($max_recommendations > 50)) {
            throw new \InvalidArgumentException('invalid value for $max_recommendations when calling RecommendationRequest., must be smaller than or equal to 50.');
        }
        if (($max_recommendations < 1)) {
            throw new \InvalidArgumentException('invalid value for $max_recommendations when calling RecommendationRequest., must be bigger than or equal to 1.');
        }

        $this->container['max_recommendations'] = $max_recommendations;

        return $this;
    }

    /**
     * Gets exclude_product_ids
     *
     * @return string[]|null
     */
    public function getExcludeProductIds()
    {
        return $this->container['exclude_product_ids'];
    }

    /**
     * Sets exclude_product_ids
     *
     * @param string[]|null $exclude_product_ids exclude_product_ids
     *
     * @return self
     */
    public function setExcludeProductIds($exclude_product_ids)
    {
        if (is_null($exclude_product_ids)) {
            throw new \InvalidArgumentException('non-nullable exclude_product_ids cannot be null');
        }
        $this->container['exclude_product_ids'] = $exclude_product_ids;

        return $this;
    }

    /**
     * Gets product_filter
     *
     * @return array<string,mixed>|null
     */
    public function getProductFilter()
    {
        return $this->container['product_filter'];
    }

    /**
     * Sets product_filter
     *
     * @param array<string,mixed>|null $product_filter product_filter
     *
     * @return self
     */
    public function setProductFilter($product_filter)
    {
        if (is_null($product_filter)) {
            throw new \InvalidArgumentException('non-nullable product_filter cannot be null');
        }
        $this->container['product_filter'] = $product_filter;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


