<?php
/**
 * SearchProducts200ResponseDataMeta
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Savanto\AI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Savanto API
 *
 * The Savanto REST API gives you programmatic access to AI-powered search, chat, recommendations, and content management.  ## Authentication All endpoints require a valid API key passed via the `Authorization` header: ``` Authorization: Bearer <api_key> ```  Key types: - **Secret keys** (`if_sk_...`) — Full API access. Use server-side only. - **Publishable keys** (`if_pk_...`) — Limited to search, chat, and feedback. Safe for client-side.
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Savanto\AI\Model;

use \ArrayAccess;
use \Savanto\AI\ObjectSerializer;

/**
 * SearchProducts200ResponseDataMeta Class Doc Comment
 *
 * @category Class
 * @package  Savanto\AI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SearchProducts200ResponseDataMeta implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'searchProducts_200_response_data_meta';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'classification' => 'mixed',
        'enhanced' => 'bool',
        'original_text' => 'string',
        'agent_used' => 'bool',
        'usage_multiplier' => 'float',
        'fallback_used' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'classification' => null,
        'enhanced' => null,
        'original_text' => null,
        'agent_used' => null,
        'usage_multiplier' => null,
        'fallback_used' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'classification' => true,
        'enhanced' => false,
        'original_text' => false,
        'agent_used' => false,
        'usage_multiplier' => false,
        'fallback_used' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'classification' => 'classification',
        'enhanced' => 'enhanced',
        'original_text' => 'originalText',
        'agent_used' => 'agentUsed',
        'usage_multiplier' => 'usageMultiplier',
        'fallback_used' => 'fallbackUsed'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'classification' => 'setClassification',
        'enhanced' => 'setEnhanced',
        'original_text' => 'setOriginalText',
        'agent_used' => 'setAgentUsed',
        'usage_multiplier' => 'setUsageMultiplier',
        'fallback_used' => 'setFallbackUsed'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'classification' => 'getClassification',
        'enhanced' => 'getEnhanced',
        'original_text' => 'getOriginalText',
        'agent_used' => 'getAgentUsed',
        'usage_multiplier' => 'getUsageMultiplier',
        'fallback_used' => 'getFallbackUsed'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('classification', $data ?? [], null);
        $this->setIfExists('enhanced', $data ?? [], null);
        $this->setIfExists('original_text', $data ?? [], null);
        $this->setIfExists('agent_used', $data ?? [], null);
        $this->setIfExists('usage_multiplier', $data ?? [], null);
        $this->setIfExists('fallback_used', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets classification
     *
     * @return mixed|null
     */
    public function getClassification()
    {
        return $this->container['classification'];
    }

    /**
     * Sets classification
     *
     * @param mixed|null $classification classification
     *
     * @return self
     */
    public function setClassification($classification)
    {
        if (is_null($classification)) {
            array_push($this->openAPINullablesSetToNull, 'classification');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('classification', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['classification'] = $classification;

        return $this;
    }

    /**
     * Gets enhanced
     *
     * @return bool|null
     */
    public function getEnhanced()
    {
        return $this->container['enhanced'];
    }

    /**
     * Sets enhanced
     *
     * @param bool|null $enhanced enhanced
     *
     * @return self
     */
    public function setEnhanced($enhanced)
    {
        if (is_null($enhanced)) {
            throw new \InvalidArgumentException('non-nullable enhanced cannot be null');
        }
        $this->container['enhanced'] = $enhanced;

        return $this;
    }

    /**
     * Gets original_text
     *
     * @return string|null
     */
    public function getOriginalText()
    {
        return $this->container['original_text'];
    }

    /**
     * Sets original_text
     *
     * @param string|null $original_text original_text
     *
     * @return self
     */
    public function setOriginalText($original_text)
    {
        if (is_null($original_text)) {
            throw new \InvalidArgumentException('non-nullable original_text cannot be null');
        }
        $this->container['original_text'] = $original_text;

        return $this;
    }

    /**
     * Gets agent_used
     *
     * @return bool|null
     */
    public function getAgentUsed()
    {
        return $this->container['agent_used'];
    }

    /**
     * Sets agent_used
     *
     * @param bool|null $agent_used agent_used
     *
     * @return self
     */
    public function setAgentUsed($agent_used)
    {
        if (is_null($agent_used)) {
            throw new \InvalidArgumentException('non-nullable agent_used cannot be null');
        }
        $this->container['agent_used'] = $agent_used;

        return $this;
    }

    /**
     * Gets usage_multiplier
     *
     * @return float|null
     */
    public function getUsageMultiplier()
    {
        return $this->container['usage_multiplier'];
    }

    /**
     * Sets usage_multiplier
     *
     * @param float|null $usage_multiplier usage_multiplier
     *
     * @return self
     */
    public function setUsageMultiplier($usage_multiplier)
    {
        if (is_null($usage_multiplier)) {
            throw new \InvalidArgumentException('non-nullable usage_multiplier cannot be null');
        }
        $this->container['usage_multiplier'] = $usage_multiplier;

        return $this;
    }

    /**
     * Gets fallback_used
     *
     * @return bool|null
     */
    public function getFallbackUsed()
    {
        return $this->container['fallback_used'];
    }

    /**
     * Sets fallback_used
     *
     * @param bool|null $fallback_used fallback_used
     *
     * @return self
     */
    public function setFallbackUsed($fallback_used)
    {
        if (is_null($fallback_used)) {
            throw new \InvalidArgumentException('non-nullable fallback_used cannot be null');
        }
        $this->container['fallback_used'] = $fallback_used;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


