<?php
/**
 * ThreadSearchRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Savanto\AI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Savanto API
 *
 * The Savanto REST API gives you programmatic access to AI-powered search, chat, recommendations, and content management.  ## Authentication All endpoints require a valid API key passed via the `Authorization` header: ``` Authorization: Bearer <api_key> ```  Key types: - **Secret keys** (`if_sk_...`) — Full API access. Use server-side only. - **Publishable keys** (`if_pk_...`) — Limited to search, chat, and feedback. Safe for client-side.
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Savanto\AI\Model;

use \ArrayAccess;
use \Savanto\AI\ObjectSerializer;

/**
 * ThreadSearchRequest Class Doc Comment
 *
 * @category Class
 * @package  Savanto\AI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ThreadSearchRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ThreadSearchRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'query' => 'string',
        'user_id' => 'string',
        'date_from' => 'string',
        'date_to' => 'string',
        'limit' => 'int',
        'offset' => 'int',
        'min_messages' => 'int',
        'max_messages' => 'int',
        'min_tokens' => 'int',
        'max_tokens' => 'int',
        'has_unresolved_queries' => 'bool',
        'sort_by' => 'string',
        'sort_order' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'query' => null,
        'user_id' => null,
        'date_from' => null,
        'date_to' => null,
        'limit' => null,
        'offset' => null,
        'min_messages' => null,
        'max_messages' => null,
        'min_tokens' => null,
        'max_tokens' => null,
        'has_unresolved_queries' => null,
        'sort_by' => null,
        'sort_order' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'query' => false,
        'user_id' => false,
        'date_from' => false,
        'date_to' => false,
        'limit' => false,
        'offset' => false,
        'min_messages' => false,
        'max_messages' => false,
        'min_tokens' => false,
        'max_tokens' => false,
        'has_unresolved_queries' => false,
        'sort_by' => false,
        'sort_order' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'query' => 'query',
        'user_id' => 'userId',
        'date_from' => 'dateFrom',
        'date_to' => 'dateTo',
        'limit' => 'limit',
        'offset' => 'offset',
        'min_messages' => 'minMessages',
        'max_messages' => 'maxMessages',
        'min_tokens' => 'minTokens',
        'max_tokens' => 'maxTokens',
        'has_unresolved_queries' => 'hasUnresolvedQueries',
        'sort_by' => 'sortBy',
        'sort_order' => 'sortOrder'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'query' => 'setQuery',
        'user_id' => 'setUserId',
        'date_from' => 'setDateFrom',
        'date_to' => 'setDateTo',
        'limit' => 'setLimit',
        'offset' => 'setOffset',
        'min_messages' => 'setMinMessages',
        'max_messages' => 'setMaxMessages',
        'min_tokens' => 'setMinTokens',
        'max_tokens' => 'setMaxTokens',
        'has_unresolved_queries' => 'setHasUnresolvedQueries',
        'sort_by' => 'setSortBy',
        'sort_order' => 'setSortOrder'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'query' => 'getQuery',
        'user_id' => 'getUserId',
        'date_from' => 'getDateFrom',
        'date_to' => 'getDateTo',
        'limit' => 'getLimit',
        'offset' => 'getOffset',
        'min_messages' => 'getMinMessages',
        'max_messages' => 'getMaxMessages',
        'min_tokens' => 'getMinTokens',
        'max_tokens' => 'getMaxTokens',
        'has_unresolved_queries' => 'getHasUnresolvedQueries',
        'sort_by' => 'getSortBy',
        'sort_order' => 'getSortOrder'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const SORT_BY_TIMESTAMP = 'timestamp';
    public const SORT_BY_MESSAGE_COUNT = 'message_count';
    public const SORT_BY_TOKEN_COUNT = 'token_count';
    public const SORT_ORDER_ASC = 'asc';
    public const SORT_ORDER_DESC = 'desc';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSortByAllowableValues()
    {
        return [
            self::SORT_BY_TIMESTAMP,
            self::SORT_BY_MESSAGE_COUNT,
            self::SORT_BY_TOKEN_COUNT,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSortOrderAllowableValues()
    {
        return [
            self::SORT_ORDER_ASC,
            self::SORT_ORDER_DESC,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('query', $data ?? [], null);
        $this->setIfExists('user_id', $data ?? [], null);
        $this->setIfExists('date_from', $data ?? [], null);
        $this->setIfExists('date_to', $data ?? [], null);
        $this->setIfExists('limit', $data ?? [], null);
        $this->setIfExists('offset', $data ?? [], null);
        $this->setIfExists('min_messages', $data ?? [], null);
        $this->setIfExists('max_messages', $data ?? [], null);
        $this->setIfExists('min_tokens', $data ?? [], null);
        $this->setIfExists('max_tokens', $data ?? [], null);
        $this->setIfExists('has_unresolved_queries', $data ?? [], null);
        $this->setIfExists('sort_by', $data ?? [], null);
        $this->setIfExists('sort_order', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['limit']) && ($this->container['limit'] > 100)) {
            $invalidProperties[] = "invalid value for 'limit', must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['limit']) && ($this->container['limit'] < 1)) {
            $invalidProperties[] = "invalid value for 'limit', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['offset']) && ($this->container['offset'] < 0)) {
            $invalidProperties[] = "invalid value for 'offset', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['min_messages']) && ($this->container['min_messages'] < 0)) {
            $invalidProperties[] = "invalid value for 'min_messages', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['max_messages']) && ($this->container['max_messages'] < 0)) {
            $invalidProperties[] = "invalid value for 'max_messages', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['min_tokens']) && ($this->container['min_tokens'] < 0)) {
            $invalidProperties[] = "invalid value for 'min_tokens', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['max_tokens']) && ($this->container['max_tokens'] < 0)) {
            $invalidProperties[] = "invalid value for 'max_tokens', must be bigger than or equal to 0.";
        }

        $allowedValues = $this->getSortByAllowableValues();
        if (!is_null($this->container['sort_by']) && !in_array($this->container['sort_by'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'sort_by', must be one of '%s'",
                $this->container['sort_by'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getSortOrderAllowableValues();
        if (!is_null($this->container['sort_order']) && !in_array($this->container['sort_order'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'sort_order', must be one of '%s'",
                $this->container['sort_order'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets query
     *
     * @return string|null
     */
    public function getQuery()
    {
        return $this->container['query'];
    }

    /**
     * Sets query
     *
     * @param string|null $query query
     *
     * @return self
     */
    public function setQuery($query)
    {
        if (is_null($query)) {
            throw new \InvalidArgumentException('non-nullable query cannot be null');
        }
        $this->container['query'] = $query;

        return $this;
    }

    /**
     * Gets user_id
     *
     * @return string|null
     */
    public function getUserId()
    {
        return $this->container['user_id'];
    }

    /**
     * Sets user_id
     *
     * @param string|null $user_id user_id
     *
     * @return self
     */
    public function setUserId($user_id)
    {
        if (is_null($user_id)) {
            throw new \InvalidArgumentException('non-nullable user_id cannot be null');
        }
        $this->container['user_id'] = $user_id;

        return $this;
    }

    /**
     * Gets date_from
     *
     * @return string|null
     */
    public function getDateFrom()
    {
        return $this->container['date_from'];
    }

    /**
     * Sets date_from
     *
     * @param string|null $date_from date_from
     *
     * @return self
     */
    public function setDateFrom($date_from)
    {
        if (is_null($date_from)) {
            throw new \InvalidArgumentException('non-nullable date_from cannot be null');
        }
        $this->container['date_from'] = $date_from;

        return $this;
    }

    /**
     * Gets date_to
     *
     * @return string|null
     */
    public function getDateTo()
    {
        return $this->container['date_to'];
    }

    /**
     * Sets date_to
     *
     * @param string|null $date_to date_to
     *
     * @return self
     */
    public function setDateTo($date_to)
    {
        if (is_null($date_to)) {
            throw new \InvalidArgumentException('non-nullable date_to cannot be null');
        }
        $this->container['date_to'] = $date_to;

        return $this;
    }

    /**
     * Gets limit
     *
     * @return int|null
     */
    public function getLimit()
    {
        return $this->container['limit'];
    }

    /**
     * Sets limit
     *
     * @param int|null $limit limit
     *
     * @return self
     */
    public function setLimit($limit)
    {
        if (is_null($limit)) {
            throw new \InvalidArgumentException('non-nullable limit cannot be null');
        }

        if (($limit > 100)) {
            throw new \InvalidArgumentException('invalid value for $limit when calling ThreadSearchRequest., must be smaller than or equal to 100.');
        }
        if (($limit < 1)) {
            throw new \InvalidArgumentException('invalid value for $limit when calling ThreadSearchRequest., must be bigger than or equal to 1.');
        }

        $this->container['limit'] = $limit;

        return $this;
    }

    /**
     * Gets offset
     *
     * @return int|null
     */
    public function getOffset()
    {
        return $this->container['offset'];
    }

    /**
     * Sets offset
     *
     * @param int|null $offset offset
     *
     * @return self
     */
    public function setOffset($offset)
    {
        if (is_null($offset)) {
            throw new \InvalidArgumentException('non-nullable offset cannot be null');
        }

        if (($offset < 0)) {
            throw new \InvalidArgumentException('invalid value for $offset when calling ThreadSearchRequest., must be bigger than or equal to 0.');
        }

        $this->container['offset'] = $offset;

        return $this;
    }

    /**
     * Gets min_messages
     *
     * @return int|null
     */
    public function getMinMessages()
    {
        return $this->container['min_messages'];
    }

    /**
     * Sets min_messages
     *
     * @param int|null $min_messages min_messages
     *
     * @return self
     */
    public function setMinMessages($min_messages)
    {
        if (is_null($min_messages)) {
            throw new \InvalidArgumentException('non-nullable min_messages cannot be null');
        }

        if (($min_messages < 0)) {
            throw new \InvalidArgumentException('invalid value for $min_messages when calling ThreadSearchRequest., must be bigger than or equal to 0.');
        }

        $this->container['min_messages'] = $min_messages;

        return $this;
    }

    /**
     * Gets max_messages
     *
     * @return int|null
     */
    public function getMaxMessages()
    {
        return $this->container['max_messages'];
    }

    /**
     * Sets max_messages
     *
     * @param int|null $max_messages max_messages
     *
     * @return self
     */
    public function setMaxMessages($max_messages)
    {
        if (is_null($max_messages)) {
            throw new \InvalidArgumentException('non-nullable max_messages cannot be null');
        }

        if (($max_messages < 0)) {
            throw new \InvalidArgumentException('invalid value for $max_messages when calling ThreadSearchRequest., must be bigger than or equal to 0.');
        }

        $this->container['max_messages'] = $max_messages;

        return $this;
    }

    /**
     * Gets min_tokens
     *
     * @return int|null
     */
    public function getMinTokens()
    {
        return $this->container['min_tokens'];
    }

    /**
     * Sets min_tokens
     *
     * @param int|null $min_tokens min_tokens
     *
     * @return self
     */
    public function setMinTokens($min_tokens)
    {
        if (is_null($min_tokens)) {
            throw new \InvalidArgumentException('non-nullable min_tokens cannot be null');
        }

        if (($min_tokens < 0)) {
            throw new \InvalidArgumentException('invalid value for $min_tokens when calling ThreadSearchRequest., must be bigger than or equal to 0.');
        }

        $this->container['min_tokens'] = $min_tokens;

        return $this;
    }

    /**
     * Gets max_tokens
     *
     * @return int|null
     */
    public function getMaxTokens()
    {
        return $this->container['max_tokens'];
    }

    /**
     * Sets max_tokens
     *
     * @param int|null $max_tokens max_tokens
     *
     * @return self
     */
    public function setMaxTokens($max_tokens)
    {
        if (is_null($max_tokens)) {
            throw new \InvalidArgumentException('non-nullable max_tokens cannot be null');
        }

        if (($max_tokens < 0)) {
            throw new \InvalidArgumentException('invalid value for $max_tokens when calling ThreadSearchRequest., must be bigger than or equal to 0.');
        }

        $this->container['max_tokens'] = $max_tokens;

        return $this;
    }

    /**
     * Gets has_unresolved_queries
     *
     * @return bool|null
     */
    public function getHasUnresolvedQueries()
    {
        return $this->container['has_unresolved_queries'];
    }

    /**
     * Sets has_unresolved_queries
     *
     * @param bool|null $has_unresolved_queries has_unresolved_queries
     *
     * @return self
     */
    public function setHasUnresolvedQueries($has_unresolved_queries)
    {
        if (is_null($has_unresolved_queries)) {
            throw new \InvalidArgumentException('non-nullable has_unresolved_queries cannot be null');
        }
        $this->container['has_unresolved_queries'] = $has_unresolved_queries;

        return $this;
    }

    /**
     * Gets sort_by
     *
     * @return string|null
     */
    public function getSortBy()
    {
        return $this->container['sort_by'];
    }

    /**
     * Sets sort_by
     *
     * @param string|null $sort_by sort_by
     *
     * @return self
     */
    public function setSortBy($sort_by)
    {
        if (is_null($sort_by)) {
            throw new \InvalidArgumentException('non-nullable sort_by cannot be null');
        }
        $allowedValues = $this->getSortByAllowableValues();
        if (!in_array($sort_by, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'sort_by', must be one of '%s'",
                    $sort_by,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['sort_by'] = $sort_by;

        return $this;
    }

    /**
     * Gets sort_order
     *
     * @return string|null
     */
    public function getSortOrder()
    {
        return $this->container['sort_order'];
    }

    /**
     * Sets sort_order
     *
     * @param string|null $sort_order sort_order
     *
     * @return self
     */
    public function setSortOrder($sort_order)
    {
        if (is_null($sort_order)) {
            throw new \InvalidArgumentException('non-nullable sort_order cannot be null');
        }
        $allowedValues = $this->getSortOrderAllowableValues();
        if (!in_array($sort_order, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'sort_order', must be one of '%s'",
                    $sort_order,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['sort_order'] = $sort_order;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


